Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -2,14 +2,14 @@ name: Build, Scan, and Push Docker Image ci/cd
 
 on:
   workflow_dispatch:
+    inputs:
+      image_name:
+        description: 'Docker image name'
+        required: true
+        default: 'iac'
   push:
     paths:
       - 'Dockerfile'
-  inputs:
-    image_name:
-      description: 'Docker image name'
-      required: true
-      default: 'iac'
 
 jobs:
   build-and-scan:
@@ -20,7 +20,12 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Log in to DockerHub
-        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
+        run: |
+          if [[ -z "${{ secrets.DOCKERHUB_USERNAME }}" || -z "${{ secrets.DOCKERHUB_PASSWORD }}" ]]; then
+            echo "DockerHub credentials are missing!"
+            exit 1
+          fi
+          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
 
       - name: Build Docker image
         run: |
@@ -29,7 +34,7 @@ jobs:
       - name: Scan image with Trivy
         uses: aquasecurity/trivy-action@master
         with:
-          image-ref: '${{ inputs.image_name }}:${{ github.sha }}'
+          image-ref: "${{ inputs.image_name }}:${{ github.sha }}"
           format: 'table'
           exit-code: 1
           ignore-unfixed: true
@@ -40,5 +45,4 @@ jobs:
         run: |
           SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
           docker tag ${{ inputs.image_name }}:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:$SHORT_SHA
-          docker images
           docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:$SHORT_SHA
